tools: sync bpf.h
mainline inclusion
from mainline-v5.2-rc1
commit 4635b0ae4d26f87cf68dbab6740955dd1ad67cf4
category: feature
bugzilla: NA
CVE: NA

-------------------------------------------------------------------------

This adds BPF_PROG_TYPE_RAW_TRACEPOINT_WRITABLE, and fixes up the

	error: enumeration value ‘BPF_PROG_TYPE_RAW_TRACEPOINT_WRITABLE’ not handled in switch [-Werror=switch-enum]

build errors it would otherwise cause in libbpf.

Signed-off-by: Matt Mullins <mmullins@fb.com>
Acked-by: Yonghong Song <yhs@fb.com>
Signed-off-by: Alexei Starovoitov <ast@kernel.org>
Conflict:
	tools/include/uapi/linux/bpf.h
	tools/lib/bpf/libbpf.c
Signed-off-by: Yufen Yu <yuyufen@huawei.com>
Reviewed-by: Hou Tao <houtao1@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>