MIPS: BCM47XX: Declare early_tlb_init() static
mainline inclusion
from mainline-v6.10-rc1
commit d18419cd66835c29ac732624324b99b43f4cff1c
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/IB5RH3
CVE: NA

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d18419cd6683

--------------------------------

early_tlb_init() was local to file but not declared static,
leading to error:

arch/mips/bcm47xx/prom.c:126:6: error: no previous prototype for ‘early_tlb_init’ [-Werror=missing-prototypes]
  126 | void early_tlb_init(void)
      |      ^~~~~~~~~~~~~~

Signed-off-by: Yongzhen Zhang <zhangyongzhen@kylinos.cn>
Reviewed-by: Philippe Mathieu-Daudé <philmd@linaro.org>
Signed-off-by: Thomas Bogendoerfer <tsbogend@alpha.franken.de>