ASoC: msm8916-wcd-digital: Select REGMAP_MMIO to fix build error
mainline inclusion
from mainline-v5.1-rc1
commit 5b86fa6d2903c41c3c3dbff4def76a5b8bbe0660
category: bugfix
bugzilla: NA
CVE: NA

Fix below build error:
ERROR: "__devm_regmap_init_mmio_clk" [sound/soc/codecs/snd-soc-msm8916-digital.ko] undefined!

Signed-off-by: Axel Lin <axel.lin@ingics.com>
Acked-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
Signed-off-by: Mark Brown <broonie@kernel.org>
Signed-off-by: Hanjun Guo <guohanjun@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>