mm: Fix compilation error of mm_update_next_owner()
ascend inclusion
category: bugfix
bugzilla: 46906
CVE: NA

-------------------------------------------------

When CONFIG_MEMCG is disabled an CONFIG_MM_OWNER is enabled, we encounter
a compilation error as follows:

kernel/exit.c:399:6: error: redefinition of ‘mm_update_next_owner’
 void mm_update_next_owner(struct mm_struct *mm)
      ^~~~~~~~~~~~~~~~~~~~
In file included from kernel/exit.c:10:0:
./include/linux/sched/mm.h:128:20: note: previous definition of
‘mm_update_next_owner’ was here
 static inline void mm_update_next_owner(struct mm_struct *mm)

To fix it, let mm_update_next_owner() depend on CONFIG_MM_OWNER

Fixes: 7560b5eec37c ("ascend: mm: add an owner for mm_struct")
Signed-off-by: Tang Yizhou <tangyizhou@huawei.com>
Reviewed-by: Kefeng Wang <wangkefeng.wang@huawei.com>
Reviewed-by: Ding Tianhong <dingtianhong@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>