sw64: fix compile error with CONFIG_SUNWAY_GED=m
Sunway inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/IB73UR

--------------------------------

Fix the following errors:

ERROR: modpost: "unlock_device_hotplug" [drivers/misc/sunway-ged.ko] undefined!
ERROR: modpost: "__add_memory" [drivers/misc/sunway-ged.ko] undefined!
ERROR: modpost: "lock_device_hotplug" [drivers/misc/sunway-ged.ko] undefined!

Fixes: 51f31c3271e5 ("sw64: add memhotplug support for guest os")

Signed-off-by: Lei Yilong <leiyilong@wxiat.com>
Reviewed-by: He Sheng <hesheng@wxiat.com>
Signed-off-by: Gu Zitao <guzitao@wxiat.com>