drivers/crypto/ccp: fix a build error
openEuler inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/IB0VHS
CVE: NA

--------------------------------

include/linux/psp-hygon.h:435:1: error: conflicting types for 'vpsp_try_do_cmd'; have 'int(int,  phys_addr_t,  struct vpsp_ret *)' {aka 'int(int,  long long unsigned int,  struct vpsp_ret *)'}
  435 | vpsp_try_do_cmd(int cmd, phys_addr_t phy_addr,
      | ^~~~~~~~~~~~~~~
include/linux/psp-hygon.h:431:1: note: previous definition of 'vpsp_try_do_cmd' with type 'int(uint32_t,  int,  void *, struct vpsp_ret *)' {aka 'int(unsigned int,  int,  void *, struct vpsp_ret *)'}
  431 | vpsp_try_do_cmd(uint32_t vid, int cmd,
      | ^~~~~~~~~~~~~~~

Fixes: 3ce4cb81ef2b ("drivers/crypto/ccp: support TKM run on CSV")
Signed-off-by: Geliang Tang <tanggeliang@kylinos.cn>