mmap: fix a compiling error for 'MAP_PA32BIT'
hulk inclusion
category: bugfix
bugzilla: NA
CVE: NA

MAP_PA32BIT was defined in uapi/asm-generic/mman.h, that was not
automatically included by mm/mmap.c when building on platforms such as
mips, and result in following compiling error:

	mm/mmap.c: In function ‘do_mmap’:
	mm/mmap.c:1450:14: error: ‘MAP_PA32BIT’ undeclared (first use in this function); did you mean ‘MAP_32BIT’?
	  if (flags & MAP_PA32BIT)
	              ^~~~~~~~~~~
	              MAP_32BIT
	mm/mmap.c:1450:14: note: each undeclared identifier is reported only once for each function it appears in
	make[1]: *** [scripts/Makefile.build:303: mm/mmap.o] Error 1

Fixes: e138253f2b82 ("svm: add support for allocing memory which is within 4G physical address in svm_mmap")

Signed-off-by: Zhengyuan Liu <liuzhengyuan@tj.kylinos.cn>
Signed-off-by: Bixuan Cui <cuibixuan@huawei.com>
Reviewed-by: Hanjun Guo <guohanjun@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>