MIPS: BCM47XX: include header for bcm47xx_prom_highmem_init() prototype
mainline inclusion
from mainline-v6.10-rc1
commit 34059321f4cf541d69e733cd02882d62c489bb77
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/IB5RH3
CVE: NA

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34059321f4cf

--------------------------------

bcm47xx_prom_highmem_init() is a global function declared in
arch/mips/bcm47xx/bcm47xx_private.h, but this header is not
included before the definition, causing a error:

arch/mips/bcm47xx/prom.c:134:13: error: no previous prototype for ‘bcm47xx_prom_highmem_init’ [-Werror=missing-prototypes]
  134 | void __init bcm47xx_prom_highmem_init(void)
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Yongzhen Zhang <zhangyongzhen@kylinos.cn>
Reviewed-by: Philippe Mathieu-Daudé <philmd@linaro.org>
Signed-off-by: Thomas Bogendoerfer <tsbogend@alpha.franken.de>