MIPS: RB532: Declare prom_setup_cmdline() and rb532_gpio_init() static
mainline inclusion
from mainline-v6.10-rc1
commit b796d046433b2042577d8d6c9a5d366e39095c30
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/IB5RH3
CVE: NA

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b796d046433b

--------------------------------

early_tlb_init() and rb532_gpio_init() were local to file but not declared
static, leading to error:

arch/mips/rb532/prom.c:49:13: error: no previous prototype for ‘prom_setup_cmdline’ [-Werror=missing-prototypes]
   49 | void __init prom_setup_cmdline(void)
      |             ^~~~~~~~~~~~~~~~~~
arch/mips/rb532/gpio.c:200:12: error: no previous prototype for ‘rb532_gpio_init’ [-Werror=missing-prototypes]
  200 | int __init rb532_gpio_init(void)
      |            ^~~~~~~~~~~~~~~

Signed-off-by: Yongzhen Zhang <zhangyongzhen@kylinos.cn>
Signed-off-by: Thomas Bogendoerfer <tsbogend@alpha.franken.de>