mmap: fix a compiling error for 'MAP_CHECKNODE'
hulk inclusion
category: bugfix
bugzilla: NA
CVE: NA

MAP_CHECKNODE was defined in uapi/asm-generic/mman.h, that was not
automatically included by mm/mmap.c when building on platforms such as
mips, and result in following compiling error:

    mm/mmap.c: In function ‘__do_mmap’:
    mm/mmap.c:1581:14: error: ‘MAP_CHECKNODE’ undeclared (first use in this function)
      if (flags & MAP_CHECKNODE)
                  ^
    mm/mmap.c:1581:14: note: each undeclared identifier is reported only once for each function it appears in
    scripts/Makefile.build:303: recipe for target 'mm/mmap.o' failed

Fixes: 56a22a261008 ("arm64/ascend: mm: Add MAP_CHECKNODE flag to check node hugetlb")

Signed-off-by: Bixuan Cui <cuibixuan@huawei.com>
Reviewed-by: Hanjun Guo <guohanjun@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>