clocksource/drivers/arch_timer: Fix vdso_fix compile error for arm32
hulk inclusion
category: bugfix
bugzilla: 47461
CVE: NA

-------------------------------------------------

We got compile error:

drivers/clocksource/arm_arch_timer.c: In function
'arch_counter_register':
drivers/clocksource/arm_arch_timer.c:1009:31: error: 'struct
arch_clocksource_data' has no member named 'vdso_fix'
1009 |   clocksource_counter.archdata.vdso_fix = vdso_fix;
      |                               ^
make[3]: ***
[/builds/1mzfdQzleCy69KZFb5qHNSEgabZ/scripts/Makefile.build:303:
drivers/clocksource/arm_arch_timer.o] Error 1
make[3]: Target '__build' not remade because of errors.

Fix it by guarding vdso_fix with #ifdef CONFIG_ARM64 .. #endif

Signed-off-by: Hanjun Guo <guohanjun@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>