usb: gadget: uvc: Fix ERR_PTR dereference in uvc_v4l2.c
mainline inclusion
from mainline-v6.12-rc1
commit a7bb96b18864225a694e3887ac2733159489e4b0
category: bugfix
bugzilla: https://gitee.com/src-openeuler/kernel/issues/IAYRHZ
CVE: CVE-2024-50056

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a7bb96b18864225a694e3887ac2733159489e4b0

--------------------------------

Fix potential dereferencing of ERR_PTR() in find_format_by_pix()
and uvc_v4l2_enum_format().

Fix the following smatch errors:

drivers/usb/gadget/function/uvc_v4l2.c:124 find_format_by_pix()
error: 'fmtdesc' dereferencing possible ERR_PTR()

drivers/usb/gadget/function/uvc_v4l2.c:392 uvc_v4l2_enum_format()
error: 'fmtdesc' dereferencing possible ERR_PTR()

Also, fix similar issue in uvc_v4l2_try_format() for potential
dereferencing of ERR_PTR().

Signed-off-by: Abhishek Tamboli <abhishektamboli9@gmail.com>
Link: https://lore.kernel.org/r/20240815102202.594812-1-abhishektamboli9@gmail.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Heyuan Wang <wangheyuan2@h-partners.com>